version: '3'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.sample
    depends_on: 
      - db
  db:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./backend/.env.sample
volumes:
  data:
